### ISSUE TITLE
The new Pay. admin panel: everything easy and clear

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-pay-nl#2]
> **Het nieuwe Pay. admin panel: alles makkelijk en overzichtelijk**
> De look & feel is nu in één lijn met Pay.'s nieuwe brand. Pagina's zijn logischer gegroepeerd, en pagina's die we niet meer gebruiken zijn verwijderd. Met de 'white label' functionaliteit is het mogelijk om je eigen branding te gebruiken. Zo worden het dashboard en alle e-mails met je eigen merkkleuren en logo's getoond en verstuurd. De nieuwe versie benader je via [my.pay.nl. ](http://my.pay.nl/)Login met de gegevens die je ook gebruikt om in te loggen op  [admin.pay.nl](http://admin.pay.nl/). In de komende maanden verbeteren we het Pay. admin panel verder. Stay tuned.

https://25758250.hs-sites-eu1.com/het-pay.-admin-panel-is-vernieuwd-snelle-en-flexibele-financiering-nodig

Do we need to check some links to the new dashboard in this library? Or update manuals?

**Comment by rvdsteege** [comment]
Linking to a transaction doesn't work well in the new admin: transaction details open in a iframe popup. There's not really a transaction details page to link to. For example, https://my.pay.nl/transactions/details/EX-9804-9925-6190 shows the details, but without navigation etc.

**Comment by remcotolsma** [comment]
> This PR resolves #2.
> 
> I also added the `pronamic_payment_provider_url_pay_nl` filter with a link to the new admin panel. Unfortunately, the linked page does not include the normal admin UI (header, navigation, etc.). We might get a reply to https://twitter.com/rvdsteege/status/1577946039012806656 and can always update the URL then if necessary.
> 
> > Gefeliciteerd met het nieuwe admin panel! Vraagje voor in onze [@Pronamic](https://twitter.com/pronamic) Pay plugin voor [#WordPress](https://twitter.com/hashtag/WordPress?src=hashtag_click): is er ook een mooie manier om naar een transactie te linken binnen het dashboard? Zoals https://my.pay.nl/transactions/details/1886196252X12159, maar dan mét behoud van navigatie etc.?
> 
> I've sent a reminder to [support@pay.nl](mailto:support@pay.nl) about direct linking to transactions:
> 
> > Beste Reüel,
> > Bedankt voor je bericht! Excuses dat hier via Twitter niet op is gereageerd. Ik ga je feedback doorzetten naar de collega's die verantwoordelijk zijn voor de nieuwe Admin.
> > Met vriendelijke groet / Best regards,
> > Loes Bruinenberg
> > Merchant support

- https://github.com/pronamic/wp-pronamic-pay-pay-nl/pull/3

Let's wait for a response before closing this issue.

**Comment by rvdsteege** [comment]
Updated manual at https://www.pronamicpay.com/nl/handleidingen/hoe-koppel-je-pay-nl-aan-wordpress-met-pronamic-pay/

**Comment by rvdsteege** [comment]
Reply from Pay:

> We kunnen alleen linken naar een pagina met informatie over de transactie. We hebben geen pagina die ook de menustructuur laat zien. Dit was overigens ook zo met de oude CSS.
>
> Met vriendelijke groet / Best regards,
>
> Tim Huizenga
> _2nd Line Merchant Support_
